---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 443, host: 443}] # HTTPS chef-server webui/api

suites:
  - name: chef-server
    run_list:
      - recipe[chef-server]
    attributes:
